services:
  - type: web
    name: tetrazpe-backend
    runtime: python
    buildCommand: ""
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:app
    rootDir: .
    plan: free
  - type: web
    name: tetrazpe-frontend
    runtime: node
    buildCommand: npm --prefix . install && npm --prefix . run build
    startCommand: npm --prefix . start
    rootDir: .
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://tetrazpe-backend.onrender.com 